services:
  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${HOST_PORT_80}:80"
      - "${HOST_PORT_443}:443"
    volumes:
      - ${VOL_HTML}:/usr/share/nginx/html:ro
      - ${VOL_CONF}:/etc/nginx/nginx.conf:ro